version: 0.2

env:
    variables:
        AWS_REGION_NAME: ap-northeast-1
        ECR_DOCKER_ENDPOINT: dkr.ecr.ap-northeast-1.amazonaws.com
        ECR_REPOSITORY_NAME: ak-notebook-prod-backend-ecr
        DOCKER_BUILDKIT: "1"
        PRODUCTION: production
    
phases:
    install:
        runtime-versions:  
            docker: 19
    pre_build:
        commands:
            - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
            - aws ecr --region ap-northeast-1 get-login-password | docker login --username AWS --password-stdin https://${AWS_ACCOUNT_ID}.${ECR_DOCKER_ENDPOINT}
            - REPOSITORY_URI=${AWS_ACCOUNT_ID}.${ECR_DOCKER_ENDPOINT}/${ECR_REPOSITORY_NAME}
            # タグ名にGitのコミットハッシュを利用
            - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
            # 事前準備: trivyをインストール
            - TRIVY_VERSION=$(curl -sS https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
            - rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.rpm
            # 事前準備: dockleをインストール
            - DOCKLE_VERSION=$(curl -sS https://api.github.com/repos/goodwithtech/dockle/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
            - rpm -ivh https://github.com/goodwithtech/dockle/releases/download/v${DOCKLE_VERSION}/dockle_${DOCKLE_VERSION}_Linux-64bit.rpm
       
    build:
        commands:
            - docker image build -t ${REPOSITORY_URI}:${IMAGE_TAG} --target ${PRODUCTION} .

    post_build:
        commands:
            # trivyによるイメージスキャン(結果格納用)
            - trivy --format json --output trivy_results.json --exit-code 0 --no-progress ${REPOSITORY_URI}:${IMAGE_TAG}
            # trivyによるイメージスキャン(CRITICALレベルの脆弱性ある場合はBuild強制終了)
            - trivy --exit-code 1 --severity CRITICAL --no-progress ${REPOSITORY_URI}:${IMAGE_TAG}
            - exit `echo $?`
            # dockleによるイメージチェック(FATALレベルの脆弱性ある場合はBuild強制終了)
            - dockle --format json -o dockle_results.json --exit-code 1 --exit-level "FATAL" ${REPOSITORY_URI}:${IMAGE_TAG}
            - exit `echo $?`
            # DockerイメージをECRへプッシュ
            - docker image push ${REPOSITORY_URI}:${IMAGE_TAG}
            # イメージURLを記録したJSONを作成
            - printf '{"name":"%s","ImageURI":"%s"}' $ECR_REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
    files:
        - imageDetail.json
        - trivy_results.json
        - dockle_results.json